services:
    app.company.twig_extension:
        class: WH\CmsBundle\Twig\CompanyExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    app.txt.twig_extension:
      class: WH\CmsBundle\Twig\TxtExtension
      arguments: ['@service_container']
      tags:
        - { name: twig.extension }